/**
 * Counter photography.
 *
 * Every item on the counter has its own real photograph, downloaded once from a
 * commercially-licensed source and committed to this repository under
 * `public/media/concessions/`. No item shares a photograph with another, and
 * the running application never requests an image from a remote host.
 *
 * Full attribution, licence and download date for each file is in
 * `docs/concession-image-sources.md`.
 *
 * Generated by `scripts/build-concession-media.mjs`.
 */

export interface ConcessionPhoto {
  itemId: string;
  /** Local path without width or extension. */
  basePath: string;
  widths: number[];
  alt: string;
  creator: string;
  provider: string;
  licence: string;
  licenceUrl: string;
  sourcePage: string;
  originalDimensions: string;
  downloadedAt: string;
}

export const concessionPhotos: ConcessionPhoto[] = [
  {
    itemId: 'con-popcorn-salt-r',
    basePath: '/media/concessions/popcorn-salt-r',
    widths: [480, 800],
    alt: 'A carton of freshly popped salted popcorn',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5956203/free-public-domain-cc0-photo',
    originalDimensions: '1024×768',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-popcorn-salt-l',
    basePath: '/media/concessions/popcorn-salt-l',
    widths: [480, 800, 1200],
    alt: 'A large tub of popcorn',
    creator: 'HeatherLion at English Wikipedia',
    provider: 'wikimedia',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=44524042',
    originalDimensions: '2592×1936',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-popcorn-caramel',
    basePath: '/media/concessions/popcorn-caramel',
    widths: [480, 800],
    alt: 'Caramel-coated popcorn',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/3294449/free-photo-image-cake-images-caramel',
    originalDimensions: '1024×683',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-popcorn-cheese',
    basePath: '/media/concessions/popcorn-cheese',
    widths: [480, 800],
    alt: 'Cheese-dusted popcorn',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5911262/image-public-domain-food-free',
    originalDimensions: '1024×768',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-cola-r',
    basePath: '/media/concessions/cola-r',
    widths: [480, 800, 1200],
    alt: 'A glass of cola over ice',
    creator: 'Reiner Schubert',
    provider: 'wikimedia',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=14485670',
    originalDimensions: '4641×3094',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-cola-l',
    basePath: '/media/concessions/cola-l',
    widths: [480, 800, 1200],
    alt: 'A large soft drink in a paper cup',
    creator: 'Michael Pardo from Niagara, Canada',
    provider: 'wikimedia',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=189867052',
    originalDimensions: '1620×1080',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-lassi',
    basePath: '/media/concessions/lassi',
    widths: [480, 800],
    alt: 'A tall glass of sweet lassi',
    creator: 'Jakub Kapusnak',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/447779/strawberry-smoothie',
    originalDimensions: '1024×683',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-lemon-soda',
    basePath: '/media/concessions/lemon-soda',
    widths: [480, 800],
    alt: 'A glass of lemon soda with fresh lime',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5922645/photo-image-background-public-domain-food',
    originalDimensions: '1024×683',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-tea',
    basePath: '/media/concessions/tea',
    widths: [480, 800, 1200],
    alt: 'A cup of masala tea',
    creator: 'Muntaha Maryum',
    provider: 'wikimedia',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=145165975',
    originalDimensions: '3600×2400',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-samosa',
    basePath: '/media/concessions/samosa',
    widths: [480, 800, 1200],
    alt: 'Fried vegetable samosas',
    creator: 'Marajozkee',
    provider: 'wikimedia',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=74633598',
    originalDimensions: '4032×3024',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-chicken-roll',
    basePath: '/media/concessions/chicken-roll',
    widths: [480, 800],
    alt: 'A chicken roll in a paratha wrap',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5952239/free-public-domain-cc0-photo',
    originalDimensions: '1024×736',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-nachos',
    basePath: '/media/concessions/nachos',
    widths: [480, 800, 1200],
    alt: 'Corn chips with warm cheese sauce',
    creator: 'JIP',
    provider: 'wikimedia',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=24636324',
    originalDimensions: '4032×3024',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-mishti',
    basePath: '/media/concessions/mishti',
    widths: [480, 800, 1200],
    alt: 'An assortment of Bengali sweets',
    creator: 'Prashant Sahu',
    provider: 'wikimedia',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourcePage: 'https://commons.wikimedia.org/w/index.php?curid=40894863',
    originalDimensions: '1536×1024',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-choc-icecream',
    basePath: '/media/concessions/choc-icecream',
    widths: [480, 800, 1200],
    alt: 'A serving of chocolate ice cream',
    creator: 'shirishpoudel07',
    provider: 'wordpress',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://wordpress.org/photos/photo/3868dc0bd6/',
    originalDimensions: '1536×2048',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-combo-two',
    basePath: '/media/concessions/combo-two',
    widths: [480, 800],
    alt: 'Popcorn and drinks for two',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5909473/image-public-domain-free-movie',
    originalDimensions: '1024×683',
    downloadedAt: '2026-08-03',
  },
  {
    itemId: 'con-combo-family',
    basePath: '/media/concessions/combo-family',
    widths: [480, 800],
    alt: 'A sharing spread of cinema snacks',
    creator: 'Unknown',
    provider: 'rawpixel',
    licence: 'CC CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourcePage: 'https://www.rawpixel.com/image/5923596/photo-image-public-domain-wood-food',
    originalDimensions: '1024×938',
    downloadedAt: '2026-08-03',
  },
];

export const concessionPhotoById = new Map(concessionPhotos.map((p) => [p.itemId, p]));
