/**
 * Counter imagery — AI-generated.
 *
 * Every item on the counter has its own generated food photograph, produced
 * once with OpenAI GPT-4o image generation (ChatGPT) on 2026-08-04 and committed to this repository under
 * `public/media/concessions/`. No item shares an image with another, and the
 * running application never requests an image from a remote host.
 *
 * These are *illustrations*, not photographs of real GrandPlex servings — the
 * customer-facing disclosure says so (see `trailer`/`concessions.aiDisclosure`
 * in the i18n resources). Full prompts, the shared art direction and the review
 * record are in `docs/concession-ai-image-manifest.md`.
 *
 * Generated by `scripts/build-concession-ai-media.mjs`. Do not edit by hand.
 */

export interface GeneratedConcessionImage {
  itemId: string;
  /** Local path without width or extension. */
  basePath: string;
  widths: number[];
  alt: string;
  sourceType: 'ai-generated';
  /** The image-generation model. */
  model: string;
  /** ISO date the set was produced. */
  generatedAt: string;
  /** The distinctive subject clause; shared direction lives in the doc. */
  prompt: string;
  aspectRatio: '4:3';
  /** Always true: a generated representation, not a real serving. */
  illustrative: true;
}

export const concessionImages: GeneratedConcessionImage[] = [
  {
    itemId: 'con-chicken-roll',
    basePath: '/media/concessions/chicken-roll',
    widths: [480, 800, 1200],
    alt: 'A chicken roll in a flaky paratha wrap',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A single chicken roll in a flaky paratha wrap, cut to show spiced chicken, onion and green chilli, on a dark slate board.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-choc-icecream',
    basePath: '/media/concessions/choc-icecream',
    widths: [480, 800, 1200],
    alt: 'A tub of chocolate ice cream with a wooden spoon',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A single scoop of dark chocolate ice cream in a paper tub, wooden spoon across the rim, softening at one edge, cool crisp light.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-cola-l',
    basePath: '/media/concessions/cola-l',
    widths: [480, 800, 1200],
    alt: 'A large cup of cola over ice',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'One noticeably tall large cup of cola over ice in a matte charcoal cup, shot straight on, a second empty cup out of focus behind.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-cola-r',
    basePath: '/media/concessions/cola-r',
    widths: [480, 800, 1200],
    alt: 'A regular cup of cola over ice',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'One regular-size cup of dark cola over ice in a matte cream paper cup with a domed lid and straw, a single medium serving.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-combo-family',
    basePath: '/media/concessions/combo-family',
    widths: [480, 800, 1200],
    alt: 'A family sharing set: two popcorns, four drinks and nachos',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A family set of exactly seven items — two large popcorns (one salted, one caramel), four colas and one nachos — from above.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-combo-two',
    basePath: '/media/concessions/combo-two',
    widths: [480, 800, 1200],
    alt: 'A sharing set: one large popcorn and two colas on a tray',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A sharing set of exactly three items — one large popcorn and two regular colas — on a tray, all countable.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-lassi',
    basePath: '/media/concessions/lassi',
    widths: [480, 800, 1200],
    alt: 'A tall glass of sweet lassi topped with cardamom and saffron',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Sweet lassi in a tall clear glass tumbler, opaque cream body, frothy collar, cardamom and saffron, diffused backlight.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-lemon-soda',
    basePath: '/media/concessions/lemon-soda',
    widths: [480, 800, 1200],
    alt: 'A glass of fizzy lemon soda with a lemon wheel',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Lemon soda in a tall clear highball, pale straw and fizzy, a lemon wheel on the rim and a small dish of salt, bright cool backlight.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-mishti',
    basePath: '/media/concessions/mishti',
    widths: [480, 800, 1200],
    alt: 'A box of four Bengali milk sweets',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Exactly four Bengali milk sweets in a kraft box, one lifted on a fork to show the grainy texture.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-nachos',
    basePath: '/media/concessions/nachos',
    widths: [480, 800, 1200],
    alt: 'Tortilla chips with cheese sauce and pickled chillies on the side',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Tortilla chips in a paper boat with a separate ramekin of cheese sauce and a ramekin of pickled chilli — sauce on the side, high angle.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-popcorn-caramel',
    basePath: '/media/concessions/popcorn-caramel',
    widths: [480, 800, 1200],
    alt: 'A cone of glossy caramel-coated popcorn',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Caramel popcorn with a glossy amber lacquer, in a paper cone in a metal holder, lit warmer than plain popcorn.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-popcorn-cheese',
    basePath: '/media/concessions/popcorn-cheese',
    widths: [480, 800, 1200],
    alt: 'A tray of orange cheddar-dusted popcorn',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Cheddar cheese popcorn dusted vivid orange in a shallow wide tray, high three-quarter angle, cool light to keep the orange truthful.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-popcorn-salt-l',
    basePath: '/media/concessions/popcorn-salt-l',
    widths: [480, 800, 1200],
    alt: 'A large tub of salted popcorn to share',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A tall large-size round tub of salted popcorn, generous enough for three, shot lower and wider so its greater size reads.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-popcorn-salt-r',
    basePath: '/media/concessions/popcorn-salt-r',
    widths: [480, 800, 1200],
    alt: 'A single carton of freshly popped salted popcorn',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'A single regular-size portion of salted popcorn in a small kraft carton, one-person portion, lit from the left.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-samosa',
    basePath: '/media/concessions/samosa',
    widths: [480, 800, 1200],
    alt: 'Two vegetable samosas, one broken open to show the filling',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Exactly two golden vegetable samosas, one broken open to show the potato-and-pea filling, a pot of tamarind chutney beside.',
    aspectRatio: '4:3',
    illustrative: true,
  },
  {
    itemId: 'con-tea',
    basePath: '/media/concessions/tea',
    widths: [480, 800, 1200],
    alt: 'A glass of hot masala tea with whole spices',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT-4o image generation (ChatGPT)',
    generatedAt: '2026-08-04',
    prompt: 'Hot masala chai in a small glass cup on a dark saucer, milky amber with a wisp of steam, whole spices on the saucer, warm moody light.',
    aspectRatio: '4:3',
    illustrative: true,
  },
];

export const concessionImageById = new Map(concessionImages.map((image) => [image.itemId, image]));
