/**
 * Offer artwork — AI-generated.
 *
 * Five screenprinted poster illustrations, produced once with OpenAI GPT image generation (ChatGPT) on
 * 2026-09-05 and committed under `public/media/offers/`. No offer shares
 * artwork with another, and the running application never requests an image
 * from a remote host.
 *
 * Illustration rather than photography on purpose: a promotion is not a place
 * or a thing, so photographing one would mean inventing a scene or reaching for
 * stock. It also keeps the three image sets legible — foyers and the counter
 * are photographs, offers are prints.
 *
 * **The figures are not in the pictures.** Every prompt forbade lettering, and
 * each composition was generated with an empty region. The amount is rendered
 * as real text over that region by `OfferArtwork` — crisp, selectable, and
 * shown in Bengali numerals in Bangla. `textAnchor` is the region that was
 * left open, `textAlign` where in it, and `textTone` the ink that reads there.
 *
 * Provenance, art direction and the review checklist:
 * `docs/offer-ai-image-manifest.md`.
 *
 * Generated by `scripts/build-offer-media.mjs`. Do not edit by hand.
 */

export interface GeneratedOfferImage {
  offerId: string;
  /** Local path without width or extension. */
  basePath: string;
  widths: number[];
  alt: string;
  /** Which half of the composition was deliberately left free of detail. */
  textAnchor: 'left' | 'right';
  /** And where in that half — the clear region is not always vertically centred. */
  textAlign: 'top' | 'center' | 'bottom';
  /** Whether that region is light or dark, and so which ink reads on it. */
  textTone: 'ink' | 'paper';
  sourceType: 'ai-generated';
  model: string;
  generatedAt: string;
  prompt: string;
  aspectRatio: '16:9';
  illustrative: true;
}

export const offerImages: GeneratedOfferImage[] = [
  {
    offerId: 'off-family-four',
    basePath: '/media/offers/off-family-four',
    widths: [640, 1024, 1600],
    alt: 'A screenprinted poster: four cinema seats side by side, two large and two small, sharing one box of popcorn',
    textAnchor: 'right',
    textAlign: 'top',
    textTone: 'ink',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-05',
    prompt: 'Four cinema seats seen straight on — two adult-height, two child-height — with one shared popcorn box on the middle armrest. Upper right left open.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    offerId: 'off-late-repertory',
    basePath: '/media/offers/off-late-repertory',
    widths: [640, 1024, 1600],
    alt: 'A screenprinted poster: a projector throwing a red beam across a darkened auditorium to a blank screen, a crescent moon above',
    textAnchor: 'left',
    textAlign: 'bottom',
    textTone: 'paper',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-05',
    prompt: 'A projector in the upper left throwing a hard-edged wedge of light diagonally to a blank screen at the lower right, seat backs below, a crescent moon in the dark. Lower left left open.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    offerId: 'off-matinee',
    basePath: '/media/offers/off-matinee',
    widths: [640, 1024, 1600],
    alt: 'A screenprinted poster: an oversized clock reading just before three, throwing a red beam over rows of cinema seats',
    textAnchor: 'right',
    textAlign: 'center',
    textTone: 'ink',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-05',
    prompt: 'An oversized clock face cropped by the left edge, hands a few minutes before three, over a simplified row of cinema seat backs. Right third left open.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    offerId: 'off-sensory',
    basePath: '/media/offers/off-sensory',
    widths: [640, 1024, 1600],
    alt: 'A screenprinted poster: a pendant house light lit to only half its cone, with sound waves fading away beside it',
    textAnchor: 'left',
    textAlign: 'center',
    textTone: 'ink',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-05',
    prompt: 'A pendant house light hanging from the top edge, its light cone filled to only half its height, with diminishing concentric sound arcs beside it. Left half left open.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    offerId: 'off-student-weeknight',
    basePath: '/media/offers/off-student-weeknight',
    widths: [640, 1024, 1600],
    alt: 'A screenprinted poster: a red lanyard and blank identity card hung over the back of a cinema seat',
    textAnchor: 'left',
    textAlign: 'center',
    textTone: 'ink',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-05',
    prompt: 'A cinema seat seen from behind at the right, a lanyard draped over its back with a completely blank identity card hanging from it. Left half left open.',
    aspectRatio: '16:9',
    illustrative: true,
  },
];

export const offerImageById = new Map(offerImages.map((image) => [image.offerId, image]));
