/**
 * Venue imagery — AI-generated.
 *
 * Each of the five houses has its own generated foyer photograph, produced
 * once with OpenAI GPT image generation (ChatGPT) on 2026-09-04 and committed to this repository under
 * `public/media/venues/`. No house shares an image with another, and the
 * running application never requests an image from a remote host.
 *
 * These are *illustrations*, not photographs of real rooms — GrandPlex is a
 * demonstration and its venues do not exist. That is precisely why generating
 * them is legitimate where generating a film poster is not: an image of a
 * fictional lobby misrepresents nobody, while a poster is real studio artwork
 * and a still contains real faces.
 *
 * The customer-facing disclosure says so on every cinema page. Full prompts,
 * the shared art direction and the review record are in
 * `docs/venue-ai-image-manifest.md`.
 *
 * Generated by `scripts/build-venue-media.mjs`. Do not edit by hand.
 */

export interface GeneratedVenueImage {
  cinemaSlug: string;
  /** Local path without width or extension. */
  basePath: string;
  widths: number[];
  alt: string;
  sourceType: 'ai-generated';
  /** The image-generation model. */
  model: string;
  /** ISO date the set was produced. */
  generatedAt: string;
  /** The distinctive subject clause; shared direction lives in the doc. */
  prompt: string;
  aspectRatio: '16:9';
  /** Always true: a generated representation, not a real room. */
  illustrative: true;
}

export const venueImages: GeneratedVenueImage[] = [
  {
    cinemaSlug: 'agrabad',
    basePath: '/media/venues/agrabad',
    widths: [640, 1024, 1600],
    alt: 'The Agrabad foyer five floors up, its full-height window looking out over the container port',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-04',
    prompt: 'A cinema foyer on the fifth floor of a port-city building, one enormous window looking out over a working container port in cool late-afternoon light, three auditorium doors.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    cinemaSlug: 'bashundhara',
    basePath: '/media/venues/bashundhara',
    widths: [640, 1024, 1600],
    alt: 'The wide single-storey Bashundhara concourse in daylight, five auditorium doors along one wall beneath a clerestory window',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-04',
    prompt: 'A wide low single-storey cinema concourse in late-morning daylight from a continuous clerestory, five auditorium doors in a row, the largest and newest lobby.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    cinemaSlug: 'dhanmondi',
    basePath: '/media/venues/dhanmondi',
    widths: [640, 1024, 1600],
    alt: 'The double-height Dhanmondi foyer at night, lit low, with a mezzanine above and one auditorium door ajar',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-04',
    prompt: 'A tall double-height cinema foyer six floors up, at night, house lights kept low, mezzanine above, four auditorium doors, the oldest house in the chain.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    cinemaSlug: 'uttara',
    basePath: '/media/venues/uttara',
    widths: [640, 1024, 1600],
    alt: 'The small Uttara foyer in late-morning sun, street glazing throwing long shadows across the carpet',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-04',
    prompt: 'A small low-ceilinged street-level cinema foyer in raking late-morning sun through a glazed shopfront, three auditorium doors, a neighbourhood house.',
    aspectRatio: '16:9',
    illustrative: true,
  },
  {
    cinemaSlug: 'zindabazar',
    basePath: '/media/venues/zindabazar',
    widths: [640, 1024, 1600],
    alt: 'The narrow Zindabazar foyer at dusk, two auditorium doors and a window onto the lit high street below',
    sourceType: 'ai-generated',
    model: 'OpenAI GPT image generation (ChatGPT)',
    generatedAt: '2026-09-04',
    prompt: 'The narrowest cinema foyer in the chain, third floor above a high street at dusk, two auditorium doors, heavily worn carpet, street lights as soft bokeh through the window.',
    aspectRatio: '16:9',
    illustrative: true,
  },
];

export const venueImageBySlug = new Map(venueImages.map((image) => [image.cinemaSlug, image]));
